version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build(deps)
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directories:
      - /src/golang/basics
      - /src/golang/advanced
      - /src/golang/tasks
      - /src/golang/dsa
    schedule:
      interval: weekly
    commit-message:
      prefix: build(deps)
    groups:
      gomod-minor-patch:
        update-types:
          - minor
          - patch
